services:
  create-astral:
    image: ghcr.io/maxi0604/create-astral:v2.1.2
    environment:
        EULA: "FALSE"
        RCON_PASSWORD: "hunter2"
    ports:
      - 25565:25565
    volumes:
      - ./ops.json:/data/ops.json:z
      - ./banned-players.json:/data/banned-players.json:z
      - ./banned-ips.json:/data/banned-ips.json:z
      - ./server.properties:/init/server.properties:z
      - ./rcon.yaml:/etc/rcon.yaml:z
      - astral-world:/data/world:z
      - astral-backup:/data/backup:z
volumes:
  astral-world:
  astral-backup:

networks:
  default:
    enable_ipv6: true
